version: '3'

services:

  web:
    build: .
    container_name: django_container
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=codelap.settings
